name    'example42-splunk'
version '2.0.5'
author  'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source  'https://github.com/example42/puppet-splunk'
summary 'Puppet module for splunk'
description 'This module installs and manages splunk. Check README for details. Puppi, monitor and firewall dependencies are needed only if the relevant features are enabled'
dependency 'example42/puppi', '>= 2.0.0'
